# -----------------------------------------------------------------------------
# Regression
# -----------------------------------------------------------------------------

[regression]
path = "@path @format /space/users/ci_wiliot/vw_e0_nightly_regression/regressions"
max_parallel_runs = 10

# -----------------------------------------------------------------------------
# Logs
# -----------------------------------------------------------------------------

[regression.logs]
path = "@path @format {this.regression.path}/logs"
prev = "@path @format {this.regression.logs.path}/prev"
latest = "@path @format {this.regression.logs.path}/latest"

# -----------------------------------------------------------------------------
# Runtime
# -----------------------------------------------------------------------------

[regression.runtime]
path = "@path @format {this.regression.path}/nightly"

# -----------------------------------------------------------------------------
# Logs - Files
# -----------------------------------------------------------------------------

[regression.logs.files.rerun_list]
name = "rerun_list"
filename = "rerun_list.cfg"
directory = "@path @format {this.regression.logs.latest}"
description = ""


[regression.logs.files.regression_summary]
name = "regression_summary"
filename =  "regression_summary.log"
directory = "@path @format {this.regression.logs.latest}"
description = ""


[regression.logs.files.errors_summary]
name = "errors_smmary"
filename = "errors_summary.log"
directory = "@path @format {this.regression.logs.latest}"
description = ""


[regression.logs.files.failure_history]
name = "failure_history"
filename = "failed_tests_history.log"
directory = "@path @format {this.regression.logs.latest}"
description = ""

# -----------------------------------------------------------------------------
# Runtime - Files
# -----------------------------------------------------------------------------

[[regression.runtime.files]]
name = "soc_rgr_db_pickled"
filename="socRgrDB.pyclass"
