# -----------------------------------------------------------------------------
# Validators
# -----------------------------------------------------------------------------
#
# Validations done upon reading settings.
#
# For reference regarding available validators to use for new 
# definitions see 
# (https://github.com/toml-lang/toml/blob/master/toml.abnf)
#
# -----------------------------------------------------------------------------

[converter]

source = "{must_exist = true}"
target = "{must_exist = true}"
include = 
