# -----------------------------------------------------------------------------
# Path
# -----------------------------------------------------------------------------
#
# Note the difference between [foo] and [[foo]].
#
# [foo] represents a table (json examples below), whereas [[foo]] 
# represents an array of tables.
#
# To illustrate the difference consider the following example:
#
#   [foo]
#   bar = 'bazz'
#   array = false
#
# In json, this would be:
#
#   {
#       'foo': {
#           'bar': 'bazz',
#           'array': 'false'
#       }
#   }
#
# On the other hand, the following definition:
#
#   [[foo]]
#   bar = 'bazz'
#   array = false
#   
# Would translate in json to:
#
#   {
#       'foo': [
#           { 'bar': 'bazz', 'array': 'false' }
#       ]
#   }
#
# what this means is that arrays allows us to define multiple objects
# of the same type with different properties:
#
#   [[converter]]
#   source = 'foo/bar'
#   target = 'bazz'
#
#   [converter.options]
#   collision = "keep"
#
#   [[converter]] # Note that this is only allowed for table-arrays
#   
#
#   [[converter]]
#   source = 'bazz/bar'
#   target = 'foo'
# 
# would translate in json to:
#
#   {
#       converter: [
#           {
#               'source': 'foo/bar', 
#               'target': 'bazz', 
#               'options': {'collision': 'keep'}
#           },
#
#           { 
#           
#           },
#
#           {
#               'source': 'bazz/bar', 
#               'target': 'foo', 
#           }
#       ]
#   }
#   
# -----------------------------------------------------------------------------


